[package]
name = "saigon_source_basecamp"
version = "0.1.0"
authors = ["Marshall Bowers <elliott.codes@gmail.com>"]
edition = "2018"

[dependencies]
saigon_core = { path = "../saigon_core" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
